import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider} from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs" ;
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

const inter = Inter({subsets: ["latin"]});
export const metadata = {
  title: "VocaAI - A career coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: "dark",
    }}
    >
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} `}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header />
            <main className="min-h-screen ">
            {children}
            </main>
            <Toaster richColors />
            {/* footer */}
            <footer className="flex items-center justify-center w-full h-20 border-t">
              <p className="text-sm text-muted-foreground">
                Made with 🧡 by Aakanksha
              </p>
            </footer>
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
